// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2kj8fO4YxGIvqMEfPX0hTvz7CorwRlSQ',
    appId: '1:358709916527:web:ed9582cfe07c412ed06e9a',
    messagingSenderId: '358709916527',
    projectId: 'upt-tutoria-app',
    authDomain: 'upt-tutoria-app.firebaseapp.com',
    storageBucket: 'upt-tutoria-app.firebasestorage.app',
    measurementId: 'G-433ZJ3FY01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlFhRj2BrAiGtsVuLT1oIk1akJrfwBN6s',
    appId: '1:358709916527:android:08968abda1a39131d06e9a',
    messagingSenderId: '358709916527',
    projectId: 'upt-tutoria-app',
    storageBucket: 'upt-tutoria-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2kj8fO4YxGIvqMEfPX0hTvz7CorwRlSQ',
    appId: '1:358709916527:web:abbac1a5ed88d35ad06e9a',
    messagingSenderId: '358709916527',
    projectId: 'upt-tutoria-app',
    authDomain: 'upt-tutoria-app.firebaseapp.com',
    storageBucket: 'upt-tutoria-app.firebasestorage.app',
    measurementId: 'G-D8ZLV3HPCC',
  );

}