name: upt_tutoria_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.4.7
  firebase_auth: ^5.3.4
  intl: ^0.18.1
  pdf: ^3.10.6
  printing: ^5.11.1
  url_launcher: ^6.2.2
  fl_chart: ^0.65.0
  csv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

flutter_launcher_icons:
  android: true 
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
